language: node_js
node_js:
  - "stable"
before_install:
  - npm update
install:
  - npm install
cache:
  directories:
    - "node_modules"
script:
  - npm run test -- --verbose=true
  - npm run coveralls
